spring.application.name=atenciones

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@fullstack1_high?TNS_ADMIN=/Users/nicom/OneDrive/Desktop/TercerSemestre/FullStack1/Wallet_fullstack1
spring.datasource.username=ADMIN
spring.datasource.password=1Ecad6a45678
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect


logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG
